version: "3"
services:
    social-2-telego:
        container_name: social-2-telego
        image: social-2-telego
        build:
            context: .
            dockerfile: Dockerfile
        pull_policy: never
        restart: unless-stopped
        environment:
            PORT: 8080
            DOMAIN: https://example.com
            ARTIST_DB: https://artistdb.example.com/{username}
            WHITELISTED:

            BOT_TOKEN:
            CHANNEL:

            # Webhook method
            RETRY_ATTEMPTS: 3
            WEBHOOK_TOKEN_ROTATE_INTERVAL: 24h

            # getUpdates method
            GET_UPDATE_DELAY: 3s