version: "3"
services:
    social-2-telego:
        container_name: social-2-telego
        image: alpine:latest
        restart: unless-stopped
        volumes:
            - ./.env:/.env
            - ./app:/app
        command: "/app"