version: "3"
services:
    social-2-telego:
        container_name: social-2-telego
        image: social-2-telego
        build:
            context: .
            dockerfile: Dockerfile
        pull_policy: never
        restart: unless-stopped
        environment:
            PORT: 8080

            USE_WEBHOOK: "true"
            WEBHOOK_DOMAIN: https://example.com
            WEBHOOK_SECRET:
            RETRY_SET_WEBHOOK_ATTEMPT: 3

            GET_UPDATES_INTERVAL: 3s

            BOT_TOKEN:
            ARTIST_DB_DOMAIN: https://artistdb.example.com/{username}
            ALLOWED_USERS: "username1,username2"
            TARGET_CHANNEL:

            NUM_WORKERS: 5